Repository projectacrn/acrn-kernel, pull requests merged in 2019-10, with the labels that each got.

#247 acrn/vhm: continue with the next VM if req_buf is NULL
  drivers/char/vhm/vhm_dev.c
Labels: Automerge: Pass, CI: Tracked On Pass

#250 drivers/i915: Treat COFFEELAKE as KABYLAKE to enable gvt-g on 0x3EA0 …
  drivers/gpu/drm/i915/i915_pci.c
  include/drm/i915_pciids.h
Labels: CI: Tracked On Pass, CI: pending approve

#252 Change active_hp_work position for code cleaning and add a module parameter to disable hp work.
  drivers/gpu/drm/i915/gvt/scheduler.c
  drivers/gpu/drm/i915/i915_params.c
  drivers/gpu/drm/i915/i915_params.h
Labels: CI: Tracked On Pass

#253 drm/i915/gvt: Rename disable_hp_work to disable GPU frequency adjustm…
  drivers/gpu/drm/i915/gvt/scheduler.c
  drivers/gpu/drm/i915/i915_params.c
  drivers/gpu/drm/i915/i915_params.h
Labels: CI: Tracked On Pass, CI: pending approve
