Repository projectacrn/acrn-kernel, pull requests merged in 2019-12, with the labels that each got.

#258 x86/tsc: Respect tsc command line paraemeter for clocksource_tsc_early
  arch/x86/kernel/tsc.c
Labels: CI: Tracked On Pass

#257 x86/tsc: Respect tsc command line paraemeter for clocksource_tsc_early
  arch/x86/kernel/tsc.c
Labels: CI: Tracked On Pass, CI: pending approve

#260 kernel/config: enable MACVLAN and MACVTAP for KATA
  kernel_config_sos
  kernel_config_uefi_sos
Labels: CI: Tracked On Pass

#261 kernel/config: enable MACVLAN and MACVTAP for KATA
  kernel_config_sos
  kernel_config_uefi_sos
Labels: Automerge: Pass, CI: Tracked On Pass
